language: php

php:
    - 5.3
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer selfupdate
    - composer install --dev --prefer-source;
    - cd tests
    - php -n ../vendor/bin/phpunit

script:
    - ../vendor/bin/phpunit --coverage-clover=../build/coverage.clover

after_script:
    - cd ..
    - php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover ./build/coverage.clover

notifications:
    email: false
