language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - composer install --dev
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar
 - cd tests
script:
 - ../vendor/bin/phpunit
notifications:
  email: false
