language: php

php:
  - 5.3
  - 5.4

before_install:
 - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php
 - composer install --dev
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
 - vendor/phpunit/phpunit/phpunit.php -c tests/phpunit.xml.dist

notifications:
  email: false